### ISSUE TITLE
How to start schema-registry on Windows

### ISSUE THREAD

**Issue by sonunitjsr223** [renukaradhya/confluentplatform#4]
Do you know if there is a way to start schema registry on Window. I was able to start KAFKA, ZOOKEEPER on windows but unable to start schema-registry. Any help?

Thanks

**Comment by sonunitjsr223** [comment]
This is already taken care courtesy to renukaradhya.

https://github.com/renukaradhya/confluentplatform/blob/master/bin/windows/schema-registry-run-class.bat
https://github.com/renukaradhya/confluentplatform/blob/master/bin/windows/schema-registry-start.bat

Save above bat files in **\confluent-oss-5.0.0-2.11.tar\confluent-5.0.0\bin\windows** directory and run as below:
>**schema-registry-start.bat ..\..\etc\schema-registry\schema-registry.properties**

**Comment by aksujith31** [comment]
But it is not working for me.. I'm getting the below error while starting schema-registry
" (io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig:169)
[2020-03-05 23:44:13,797] ERROR Server died unexpectedly:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain:51)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000"

Someone plz help me on this

**Comment by naveenkulkarni029** [comment]
Please help even i am getting the smae error.

**Comment by GirijaRD** [comment]
please checkC:
1. you have added schema-registry.properties files at mentioned location (you can find it at https://github.com/renukaradhya/confluentplatform/blob/master/etc/schema-registry/schema-registry.properties )
2. change listeners and kafkastore.connection.url from schema-registry.properties
kafkastore.connection.url host must be same as your **zookeeper** host
```
listeners=http://localhost:8081
kafkastore.connection.url=0.0.0.0:2181
```
